### ISSUE TITLE
add

### ISSUE THREAD

**Issue by nu0l** [pmiaowu/log4j2Scan#1]
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
	at burp.Bootstrap.YamlReader.<init>(YamlReader.java:25)
	at burp.Bootstrap.YamlReader.getInstance(YamlReader.java:31)
	at burp.Ui.Tags.<init>(Tags.java:24)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.dj6.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.Yaml
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 14 more

**Comment by pmiaowu** [comment]
你打包完以后,导入错文件了
打包以后的文件在,target文件夹里面的log4j2Scan文件夹,才是打包好的
