### ISSUE TITLE
扫描不出漏洞

### ISSUE THREAD

**Issue by JackeyLov5** [pmiaowu/log4j2Scan#13]
macos 15
burp 2024 10.3
攻防 遇到一个ua头的和一个Accept参数的log4j漏洞插件没探测到 
求师傅解答orz

**Comment by JackeyLov5** [comment]
还有就是日常错误：
java.lang.ClassNotFoundException: burp.DnsLogModule.ExtensionMethod.ceye
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at java.base/java.lang.Class.forName(Class.java:404)
	at burp.DnsLogModule.DnsLog.<init>(DnsLog.java:17)
	at burp.BurpExtender.remoteCmdExtension(BurpExtender.java:281)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:188)
	at burp.Z_5b.passiveAudit(Unknown Source)
	at burp.Zqi8.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
java.lang.ClassNotFoundException: burp.DnsLogModule.ExtensionMethod.ceye
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at java.base/java.lang.Class.forName(Class.java:404)
	at burp.DnsLogModule.DnsLog.<init>(DnsLog.java:17)
	at burp.BurpExtender.remoteCmdExtension(BurpExtender.java:281)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:188)
	at burp.Z_5b.passiveAudit(Unknown Source)
	at burp.Zqi8.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
java.lang.ClassNotFoundException: burp.DnsLogModule.ExtensionMethod.ceye
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at java.base/java.lang.Class.forName(Class.java:404)
	at burp.DnsLogModule.DnsLog.<init>(DnsLog.java:17)
	at burp.BurpExtender.remoteCmdExtension(BurpExtender.java:281)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:188)
	at burp.Z_5b.passiveAudit(Unknown Source)
	at burp.Zqi8.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
