### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by baimasi** [pmiaowu/log4j2Scan#3]
java.lang.NullPointerException
	at burp.pxd.c(Unknown Source)
	at burp.m9g.getHttpService(Unknown Source)
	at burp.teb.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.emb.b(Unknown Source)
	at burp.chb.b(Unknown Source)
	at burp.chb.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.gre.a(Unknown Source)
	at burp.chb.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1124)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:724)
	at burp.bhb.a(Unknown Source)
	at burp.bhb.insertTab(Unknown Source)
	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:798)
	at burp.bdh.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.zwf.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at burp.pxd.c(Unknown Source)
	at burp.m9g.getHttpService(Unknown Source)
	at burp.teb.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.emb.b(Unknown Source)
	at burp.chb.b(Unknown Source)
	at burp.chb.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.gre.a(Unknown Source)
	at burp.chb.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1124)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:724)
	at burp.bhb.a(Unknown Source)
	at burp.bhb.insertTab(Unknown Source)
	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:798)
	at burp.bdh.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.zwf.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pmiaowu** [comment]
你看看是不是你导入错包了,要导入/target/log4j2Scan/log4j2Scan.jar
