### ISSUE TITLE
师傅爆这个错咋解决呢

### ISSUE THREAD

**Issue by z0edff0x3d** [pmiaowu/log4j2Scan#5]
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at burp.Application.RemoteCmdExtension.RemoteCmd.init(RemoteCmd.java:63)
	at burp.Application.RemoteCmdExtension.RemoteCmd.<init>(RemoteCmd.java:41)
	at burp.BurpExtender.remoteCmdExtension(BurpExtender.java:251)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:157)
	at burp.v8.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: burp.CustomErrorException.TaskTimeoutException: scan task timed out
	at burp.Application.RemoteCmdExtension.ExtensionMethod.RemoteCmdScan.runExtension(RemoteCmdScan.java:86)
	at burp.Application.RemoteCmdExtension.ExtensionMethod.RemoteCmdScan.<init>(RemoteCmdScan.java:60)
	... 15 more
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedConstructorAccessor92.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at burp.Application.RemoteCmdExtension.RemoteCmd.init(RemoteCmd.java:63)
	at burp.Application.RemoteCmdExtension.RemoteCmd.<init>(RemoteCmd.java:41)
	at burp.BurpExtender.remoteCmdExtension(BurpExtender.java:251)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:157)
	at burp.v8.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: burp.CustomErrorException.TaskTimeoutException: scan task timed out
	at burp.Application.RemoteCmdExtension.ExtensionMethod.RemoteCmdScan.runExtension(RemoteCmdScan.java:86)
	at burp.Application.RemoteCmdExtension.ExtensionMethod.RemoteCmdScan.<init>(RemoteCmdScan.java:60)
	... 14 more
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedConstructorAccessor92.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at burp.Application.RemoteCmdExtension.RemoteCmd.init(RemoteCmd.java:63)
	at burp.Application.RemoteCmdExtension.RemoteCmd.<init>(RemoteCmd.java:41)
	at burp.BurpExtender.remoteCmdExtension(BurpExtender.java:251)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:157)
	at burp.v8.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: burp.CustomErrorException.TaskTimeoutException: scan task timed out
	at burp.Application.RemoteCmdExtension.ExtensionMethod.RemoteCmdScan.runExtension(RemoteCmdScan.java:86)
	at burp.Application.RemoteCmdExtension.ExtensionMethod.RemoteCmdScan.<init>(RemoteCmdScan.java:60)
	... 14 more

**Comment by pmiaowu** [comment]
dnslog请求失败一直在超时,你可以通过config.yaml,修改成Ceye在试试,记得查看md文件,看看如何修改的
